#!/usr/bin/env python
# -*- coding: utf-8 -*-

from PyQt4 import QtGui, QtCore

import anki.utils
import sqlalchemy

import weakref

import pinyin.anki.keys
import pinyin.factproxy
from pinyin.logger import log
import pinyin.media
import pinyin.transformations
import pinyin.utils

import utils

class Hook(object):
    def __init__(self, mw, notifier, mediamanager, config, updaterbuilders):
        self.mw = mw
        self.notifier = notifier
        self.mediamanager = mediamanager
        self.config = config
        self.updaterbuilders = updaterbuilders

    def buildupdater(self, field):
        builder = self.updaterbuilders.get(field)
        return (builder is not None) and builder(self.notifier, self.mediamanager, self.config) or None

class FocusHook(Hook):
    def __init__(self, *args):
        Hook.__init__(self, *args)
        # This hash holds the most recently seen values, by key, of the possible fields.
        # We use this to implement automatic unmarking of field contents - if the value
        # in the field upon focus lost doesn't match that upon focus coming in then its
        # most likely that they changed the field and it should no longer be considered
        # generated by the Toolkit.
        self.knownfieldcontents = {}
        # This is necessary to let us track focus-gaining events, because there is no
        # gotFocus signal :-(. Use weak references to refer to fact edits to prevent memory leak.
        self.knownfactedits = []
    
    def sessionExistsFor(self, field):
        # If there is no current deck, DO NOT ask about the field name or
        # value. This is because the session may be dead, so asking will
        # generate a sqlalchemy.exc.UnboundExecutionError
        if self.mw.deck is None or self.mw.deck.s is None:
            return False
        
        try:
            field.name
            return True
        except sqlalchemy.exc.UnboundExecutionError, e:
            return False
    
    def makeField(self, factedit, field):
        # Anki lets us hook lostFocus, but we need to go via QT for gotFocus
        self.knownfactedits.append((weakref.ref(factedit), field))
    
    def onFocusChanged(self, fromwidget, towidget):
        # SOME thing had its focus changed. We may need to report that a fact edit
        # got the focus, but we'll also take this opportunity to garbage collect
        # the fact edit -> field mapping, or we'll get progressivly slower...
        trimmedknownfactedits = []
        for knownfacteditref, field in self.knownfactedits:
            knownfactedit = knownfacteditref()
            if knownfactedit:
                # Emulation of a focus gaining event:
                self.onFocusGot(field)
                # Fact edit is still alive and kicking, so continue holding on to it...
                trimmedknownfactedits.append((knownfacteditref, field))
        
        self.knownfactedits = trimmedknownfactedits
    
    def onFocusGot(self, field):
        if not self.sessionExistsFor(field):
            return
        
        log.info("User put focus on the field %s", field.name)
        
        # Remember old field contents
        self.knownfieldcontents[field.name] = field.value
    
    def onFocusLost(self, fact, field):
        if not self.sessionExistsFor(field):
            return
        
        log.info("User moved focus from the field %s", field.name)
        
        # Check old field contents against remembered value to determine changed status..
        self.knownfieldcontents[field.name], fieldchanged = None, self.knownfieldcontents[field.name] != field.value
        
        # Changed fields have their "generated" tag stripped. NB: ALWAYS update the fact (even if the
        # field hasn't changed) because we might have changed ANOTHER field to e.g. blank it, and now
        # by moving focus from the expression field we indicate that we want to fill it out.
        #
        # NB: be careful with this ternary statement! It's perfectly OK for field.value to be "", and if
        # that happens we CAN'T let fieldvalue in updatefact be None, or autoblanking gets broken.
        self.updatefact(fact, field.name, (fieldchanged and [pinyin.factproxy.unmarkgeneratedfield(field.value)] or [None])[0])
    
    def updatefact(self, fact, fieldname, fieldvalue):
        # Are we not in a Mandarin model?
        if not(anki.utils.findTag(self.config.modelTag, fact.model.tags)):
            return
        
        # Need a fact proxy because the updater works on dictionary-like objects
        factproxy = pinyin.factproxy.FactProxy(self.config.candidateFieldNamesByKey, fact)
        
        # Find which kind of field we have just moved off
        updater = None
        for key, updateablefieldname in factproxy.fieldnames.items():
            if fieldname == updateablefieldname:
                updater = self.buildupdater(key)
                break

        # Update the card, ignoring any errors
        if updater:
            pinyin.utils.suppressexceptions(lambda: updater.updatefact(factproxy, fieldvalue))
    
    def install(self):
        from anki.hooks import addHook, removeHook
        
        # Install hook into focus event of Anki: we regenerate the model information when
        # the cursor moves from the Expression/Reading/whatever field to another field
        log.info("Installing focus hook")
        
        try:
            # On versions of Anki that still had Chinese support baked in, remove the
            # provided hook from this event before we replace it with our own:
            from anki.features.chinese import onFocusLost as oldHook
            removeHook('fact.focusLost', oldHook)
        except ImportError:
            pass
        
        # Unconditionally add our new hooks to Anki
        addHook('makeField', self.makeField)
        addHook('fact.focusLost', self.onFocusLost)
        
        # Global hook
        app = QtGui.QApplication.instance()
        app.connect(app, QtCore.SIGNAL("focusChanged(QWidget*, QWidget*)"), self.onFocusChanged)

class FieldShrinkingHook(Hook):
    def adjustFieldHeight(self, widget, field):
        for wanttoshrink in ["mw", "audio", "mwaudio"]:
            if field.name in self.config.candidateFieldNamesByKey[wanttoshrink]:
                log.info("Shrinking field %s", field.name)
                widget.setFixedHeight(30)
    
    def install(self):
        from anki.hooks import addHook
        
        log.info("Installing field height adjustment hook")
        addHook("makeField", self.adjustFieldHeight)

# Shrunk version of color shortcut plugin merged with Pinyin Toolkit to give that functionality without the seperate download.
# Original version by Damien Elmes <anki@ichi2.net>
class ColorShortcutKeysHook(Hook):
    def setColor(self, editor, i, sandhify):
        log.info("Got color change event for color %d, sandhify %s", i, sandhify)
        
        color = (self.config.tonecolors + self.config.extraquickaccesscolors)[i - 1]
        if sandhify:
            color = pinyin.transformations.sandhifycolor(color)
        
        focusededit = editor.focusedEdit()
        
        cursor = focusededit.textCursor()
        focusededit.setTextColor(QtGui.QColor(color))
        cursor.clearSelection()
        focusededit.setTextCursor(cursor)
    
    def setupShortcuts(self, editor):
        # Loop through the 8 F[x] keys, setting each one up
        # Note: Ctrl-F9 is the HTML editor. Don't do this as it causes a conflict
        log.info("Setting up shortcut keys on fact editor")
        for i in range(1, 9):
            for sandhify in [True, False]:
                keysequence = (sandhify and pinyin.anki.keys.sandhiModifier + "+" or "") + pinyin.anki.keys.shortcutKeyFor(i)
                QtGui.QShortcut(QtGui.QKeySequence(keysequence), editor.widget,
                                lambda i=i, sandhify=sandhify: self.setColor(editor, i, sandhify))
    
    def install(self):
        from anki.hooks import wrap
        import ankiqt.ui.facteditor
        
        log.info("Installing color shortcut keys hook")
        ankiqt.ui.facteditor.FactEditor.setupFields = wrap(ankiqt.ui.facteditor.FactEditor.setupFields, self.setupShortcuts, "after")
        self.setupShortcuts(self.mw.editor)

class HelpHook(Hook):
    def install(self):
        # Store the action on the class.  Storing a reference to it is necessary to avoid it getting garbage collected.
        self.action = QtGui.QAction("Pinyin Toolkit", self.mw)
        self.action.setStatusTip("Help for the Pinyin Toolkit available at our website")
        self.action.setEnabled(True)
        
        helpUrl = QtCore.QUrl(u"http://batterseapower.github.com/pinyin-toolkit/")
        self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: QtGui.QDesktopServices.openUrl(helpUrl))
        self.mw.mainWin.menuHelp.addAction(self.action)

class PreferencesHook(Hook):
    menutext = "Preferences"
    menutooltip = "Configure the Pinyin Toolkit"
    
    def triggered(self):
        # NB: must import these lazily to break a loop between preferencescontroller and here
        import pinyin.forms.preferences
        import pinyin.forms.preferencescontroller

        log.info("User opened preferences dialog")
        
        # Instantiate and show the preferences dialog modally
        preferences = pinyin.forms.preferences.Preferences(self.mw)
        controller = pinyin.forms.preferencescontroller.PreferencesController(preferences, self.notifier, self.mediamanager, self.config)
        result = preferences.exec_()
        
        # We only need to change the configuration if the user accepted the dialog
        if result == QtGui.QDialog.Accepted:
            # Update by the simple method of replacing the settings dictionaries: better make sure that no
            # other part of the code has cached parts of the configuration
            self.config.settings = controller.model.settings
            
            # Ensure this is saved in Anki's configuration
            utils.persistconfig(self.mw, self.config)
    
    def install(self):
        # Store the action on the class.  Storing a reference to it is necessary to avoid it getting garbage collected.
        self.action = QtGui.QAction("Pinyin Tool&kit Preferences", self.mw)
        self.action.setStatusTip("Configure the Pinyin Toolkit")
        self.action.setMenuRole(QtGui.QAction.PreferencesRole)
        self.action.setEnabled(True)
        
        self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.triggered())
        self.mw.mainWin.menu_Settings.addAction(self.action)

class ToolMenuHook(Hook):
    pinyinToolkitMenu = None
    
    def install(self):
        # Install menu item
        log.info("Installing a menu hook (%s)", type(self))
        
        # Build and install the top level menu if it doesn't already exist
        if ToolMenuHook.pinyinToolkitMenu is None:
            ToolMenuHook.pinyinToolkitMenu = QtGui.QMenu("Pinyin Toolkit", self.mw.mainWin.menuTools)
            self.mw.mainWin.menuTools.addMenu(ToolMenuHook.pinyinToolkitMenu)
        
        # Store the action on the class.  Storing a reference to it is necessary to avoid it getting garbage collected.
        self.action = QtGui.QAction(self.__class__.menutext, self.mw)
        self.action.setStatusTip(self.__class__.menutooltip)
        self.action.setEnabled(True)
        
        # HACK ALERT: must use lambda here, or the signal never gets raised! I think this is due to garbage collection...
        # We try and make sure that we don't run the action if there is no deck presently, to at least suppress some errors
        # in situations where the users select the menu items (this is possible on e.g. OS X). It would be better to disable
        # the menu items entirely in these situations, but there is no suitable hook for that presently.
        self.mw.connect(self.action, QtCore.SIGNAL('triggered()'), lambda: self.mw.deck is not None and self.triggered())
        ToolMenuHook.pinyinToolkitMenu.addAction(self.action)

class MassFillHook(ToolMenuHook):
    def triggered(self):
        field = self.__class__.field
        log.info("User triggered missing information fill for %s" % field)
        
        for fact in utils.suitableFacts(self.config.modelTag, self.mw.deck):
            # Need a fact proxy because the updater works on dictionary-like objects
            factproxy = pinyin.factproxy.FactProxy(self.config.candidateFieldNamesByKey, fact)
            if field not in factproxy:
                continue
            
            self.buildupdater(field).updatefact(factproxy, None, **self.__class__.updatefactkwargs)
            
            # NB: very important to mark the fact as modified (see #105) because otherwise
            # the HTML etc won't be regenerated by Anki, so users may not e.g. get working
            # sounds that have just been filled in by the updater.
            fact.setModified(textChanged=True)
        
        # For good measure, mark the deck as modified as well (see #105)
        self.mw.deck.setModified()
    
        # DEBUG consider future feature to add missing measure words cards after doing so (not now)
        self.notifier.info(self.__class__.notification)

class MissingInformationHook(MassFillHook):
    menutext = 'Fill missing card data'
    menutooltip = 'Update all the cards in the deck with any missing information the Pinyin Toolkit can provide.'
    
    field = "expression"
    updatefactkwargs = {}
    
    notification = "All missing information has been successfully added to your deck."

class ReformatReadingsHook(MassFillHook):
    menutext = 'Reformat readings'
    menutooltip = 'Update all the readings in your deck with colorisation and tones according to your preferences.'
    
    field = "reading"
    updatefactkwargs = dict(alwaysreformat = True)
    
    notification = "All readings have been successfully reformatted."

# NB: this must go at the end of the file, after all the definitions are in scope
hookbuilders = [
    # Focus hook
    FocusHook,
    # Widget adjusting hooks
    FieldShrinkingHook,
    # Keybord hooks
    ColorShortcutKeysHook,
    # Menu hooks
    HelpHook,
    PreferencesHook,
    MissingInformationHook,
    ReformatReadingsHook
  ]